package com.esprit.TechEvents;


import com.codename1.charts.util.ColorUtil;
import com.codename1.components.ImageViewer;
import com.esprit.gui.Menu;
import static com.codename1.ui.CN.*;
import com.codename1.components.SpanLabel;
import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Dialog;
import com.codename1.ui.EncodedImage;
import com.codename1.ui.Form;
import com.codename1.ui.InfiniteContainer;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Toolbar;
import com.codename1.ui.URLImage;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BoxLayout;
import com.esprit.Entity.Event;
import com.esprit.Service.ServiceEvent;
import com.esprit.gui.EditEvent;
import com.esprit.gui.ListEvent;
import java.util.ArrayList;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class TechEvents {

    private Form current;
    private static Resources theme;
    ServiceEvent es = new ServiceEvent();
    ArrayList<Event> lstEvt = new ArrayList<>();
    private Form home;
    public static Event evtStatic;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }

    public void start() {
       
        Form home = new Form();
        home.setTitle("Accueil");
        Menu.getMenu(home);
         Container list = new InfiniteContainer() {
            @Override
            public Component[] fetchComponents(int index, int amount) {
                if (index == 0) {
                    lstEvt = es.getList2();
                }
                if (index + amount > lstEvt.size()) {
                    amount = lstEvt.size() - index;
                }
                if (amount <= 0) {
                    return null;
                }
                Component[] elements = new Component[amount];

                int i = 0;
                int j = 1;
                for (Event p : lstEvt) {
                   
                    System.out.println(".fetchComponents()"+p.getStatut());
                     Label ps = new Label();
                     if(p.getStatut().equals("Annulé")){
                        p.setStatut("Annulé");
                        ps.getAllStyles().setFgColor(ColorUtil.rgb(255, 0, 0));
                    }
                    if(p.getStatut().equals("Reporté")){
                        p.setStatut("Reporté");
                        ps.getAllStyles().setFgColor(ColorUtil.rgb(204, 102, 0));
                    }
                    if(p.getStatut().equals("Terminé")){
                        p.setStatut("Terminé");
                        ps.getAllStyles().setFgColor(ColorUtil.rgb(0, 0, 255));
                    }
                    if(p.getStatut().equals("Disponible")){
                        ps.getAllStyles().setFgColor(ColorUtil.rgb(0, 102, 51));
                    }
                    ps.getAllStyles().set3DText(true, true);
                    ps.setText("            --------" + j + "--------"+p.getStatut());
                    
                    //Creating custom container
                    Container element = new Container(BoxLayout.y());
                    Container line1 = new Container(BoxLayout.x());
                    
                    EncodedImage placeholder = EncodedImage.createFromImage(TechEvents.getTheme().getImage("img1.jpg"), true);
                                     URLImage uRLImage = URLImage.createToStorage(placeholder,
                                     p.getPathphoto(),"http://127.0.0.1/image/"+p.getPathphoto());
                                     ImageViewer yimg = new ImageViewer(uRLImage);
                    
                    //ImageViewer photo = new ImageViewer(MyApplication.getTheme().getImage(p.getPathphoto()));
                    
                    
                    Label titre = new Label(p.getTitre());
                    Label statut = new Label("            "+p.getStatut());
                    titre.getAllStyles().setFgColor(ColorUtil.rgb(0, 0, 255));
                    System.out.println(".fetchComponents()" + p.getDuree());
                    Label date = new Label(p.getDateEvent().toString());
                    Label duree = new Label(p.getDuree().toString() + "J");
                    Label cptmax = new Label(p.getCapaciteMax().toString() + "Max");

                    line1.add(yimg);
                    line1.add(titre);
                    line1.add(duree);
                    line1.add(date);
                    //line1.add(cptmax);
                    //element.add(photo);
                    element.add(line1);

                    element.add(ps);
                  //  element.add(statut);
                    
                    Button b = new Button("button");
                    b.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent evt) {
                            evtStatic = p;
                            EditEvent edt = new EditEvent();
                            edt.getF().show();
                        }
                    });
                    element.setLeadComponent(b);
                    elements[i] = element;

                    //Using MultiButton
                    /*MultiButton mb = new MultiButton(p.getNom());
                    mb.setTextLine2(Integer.toString(p.getAge()));
                    mb.setTextLine3("Never show Id");
                    elements[i]=mb;*/
                    i++;
                    j++;
                }
                return elements;
            }
        };

        list.setScrollableY(false);
        home.add(list);
        home.show();
//        ListEvent aev = new ListEvent();
//        Menu.getMenu(aev.getF());
//        aev.getF().show();
        
    }

    private void showOKForm(String name) {
        Form f = new Form("Thanks", BoxLayout.y());
        f.add(new SpanLabel("Thanks " + name + " for your submission. You can press the back arrow and try again"));
        f.getToolbar().setBackCommand("", e -> home.showBack());
        f.show();
    }
    
    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

    public static Resources getTheme() {
        return theme;
    }

    public static void setTheme(Resources theme) {
        TechEvents.theme = theme;
    }

    
    
}
